:toc-title: Содержимое
:images: ./images
:icons: font

== О проекте

* Репозитории

https://github.com/gurv/vg-doc

* Инструменты

[plantuml, dev-env, png]
....
[Docker]
[Gradle] ..> [Java]
[Asciidoc] ..> [Java]
[Asciidoc] ..> [GraphViz]
[Webpack] ..> [NodeJS]
[Angular] ..> [NodeJS]
[Angular] ..> [Webpack]
....

* CI

[plantuml, CI, png]
....
[GitHub] as git
[GitHub Pages] as pages
[Travis CI] as travis
[SonarCloud] as sonar
[Sonatype OSSRH] as nexus
[DockerHub] as docker
git --> travis
travis --> sonar
travis --> nexus
travis --> docker
travis --> pages
....

== Сервисы

* Порты

[cols="2*", options="header"]
|===
|Сервис
|Порт

|config
|8888

|gateway
|10000; 8000 (Sidecar)

|auth
|5000

|account
|8081

|metadata
|8082

|h2
|8083, 9093 (TCP)

|dataflow
|9393

|swagger
|8084

|jenkins
|8085

|nexus
|8086

|monitoring
|9090 (Prometheus), 9091 (PushGateway), 9182 (WMI Exporter), 9100 (Node Exporter), 3000 (Grafana)

|streams
|2181 (Zookeeper),
9092 1234 (Kafka),
18081 (Kafka Schema Registry)

|samples
|8101 (SampleOperation), 8102 (SampleAccount)

|...
|5000 (Docker Registry)
|===

=== config

Конфигурация сервисов (

http://localhost:8888/account/default[проверка доступности]

http://localhost:8888/actuator/info[actuator]

=== auth

Авторизация

http://localhost:5000/uaa[endpoint]

=== account

Учетные записи

http://localhost:8081/db-console[db-console]

=== gateway

Шлюз

http://localhost:10000/[web-console]

=== metadata

Модель данных

http://localhost:8082/db-console[db-console]

http://localhost:8082/api/browser[HAL]

http://localhost:8082/api/entityTypes[сущности]

http://localhost:8082/entities/createRandom[создать fake]

=== h2

База данных H2

http://localhost:8083[web-console]

[TIP]
====
.Примеры значений JDBC URL:
* jdbc:h2:metadata
* jdbc:h2:tcp://localhost:9093/auth
* jdbc:h2:tcp://h2:9093/account
====

=== dataflow

Потоки данных (Kafka/Zookeeper)

http://localhost:9393/dashboard[web-console]

=== skipper

Управление приложениями

http://localhost:7577/api[API]

=== monitoring

Мониторинг

* UI:
http://localhost:3000[Grafana],
http://localhost:9090[Prometheus]

* Запуск/останов
[source]
----
gradle dockerMonitoringStart
gradle dockerMonitoringStop
----

[TIP]
====
TODO WMI Exporter: запуск из gradle

TODO WMI Exporter: доступность длч Prometheus, который в docker-контейнере (--net=host ...)

[source]
----
C:/app/wmi_exporter-0.2.10/wmi_exporter.exe
----
====


* Полезное

[plantuml, monitoring, png]
....
[Prometheus]
[Grafana]
[Prometheus]
[WMI Exporter]
[Node Exporter]
[PushGateway]
[service] << SpringBoot-application >>
[Prometheus] ..> [Prometheus]
note on link:  9090
[Prometheus] ..> [Grafana]
note on link:  3000
[Prometheus] ..> [Docker Engine]
note on link:  9323
[Prometheus] ..> [WMI Exporter]
note on link:  9182
[Prometheus] ..> [Node Exporter]
note on link:  9100
[WMI Exporter] ..> [Windows]
[Node Exporter] ..> [Unix]
[PushGateway] ..> [service]
[PushGateway] ..> [Prometheus]
....

Метрики:
http://localhost:9323/metrics[Docker],
http://localhost:3000/metrics[Grafana],
http://localhost:9090/metrics[Prometheus],
http://localhost:1233/metrics[Zookeeper],
http://localhost:1234/metrics[Kafka],
http://localhost:9393/management/prometheus[Dataflow],
http://localhost:8084/actuator/prometheus[Swagger],
http://localhost:8888/actuator/prometheus[Config],
http://localhost:10000/actuator/prometheus[Gateway],
http://localhost:8081/actuator/prometheus[Account],
http://localhost:8082/actuator/prometheus[Metadata],
http://localhost:7577/actuator/prometheus[Skipper]

Запуск Prometheus в Docker-е:
[source]
----
docker run -d -p 9090:9090 -v C:/prj/vg/prometheus/build/prometheus.yml:/etc/prometheus/prometheus.yml --name=vg-prometheus gurv/vg-prometheus
----
или
[source]
----
gradle prometheus:dockerRun
----

=== swagger

API

* Swagger
http://localhost:8084/swagger-ui.html

== Примеры

=== Операции

Ссылки:

http://localhost:8080/ping

http://localhost:8080/db-console

http://localhost:8080/browser/index.html#/

http://localhost:8080/operation

http://localhost:8080/operation/1

http://localhost:8080/operation/?size=5

http://localhost:8080/operation?page=0

http://localhost:8080/operation/search/countByTimestampLessThanEqual?ts=2019-01-01T01:30:00.000-04:00

http://localhost:8080/profile/operation

http://localhost:8080/operations/operation
